"""empty message

Revision ID: c8567fca4436
Revises: 
Create Date: 2025-12-04 15:36:34.715164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c8567fca4436'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tmdb_id', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('release_date', sa.Date(), nullable=True),
    sa.Column('rating', sa.Numeric(), nullable=True),
    sa.Column('popularity', sa.Numeric(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('backdrop_url', sa.Text(), nullable=True),
    sa.Column('genres', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tmdb_id')
    )
    op.create_table('users',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('ai_recommendations',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_ai_recs_user_movie')
    )
    op.create_index(op.f('ix_ai_recommendations_movie_id'), 'ai_recommendations', ['movie_id'], unique=False)
    op.create_index(op.f('ix_ai_recommendations_user_id'), 'ai_recommendations', ['user_id'], unique=False)
    op.create_table('dislikes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_dislikes_user_movie')
    )
    op.create_index(op.f('ix_dislikes_movie_id'), 'dislikes', ['movie_id'], unique=False)
    op.create_index(op.f('ix_dislikes_user_id'), 'dislikes', ['user_id'], unique=False)
    op.create_table('favorites',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_favorites_user_movie')
    )
    op.create_index(op.f('ix_favorites_movie_id'), 'favorites', ['movie_id'], unique=False)
    op.create_index(op.f('ix_favorites_user_id'), 'favorites', ['user_id'], unique=False)
    op.create_table('friends',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('requester_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('addressee_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'accepted', 'blocked', name='friend_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('requester_id', 'addressee_id', name='uq_friends_requester_addressee')
    )
    op.create_index(op.f('ix_friends_addressee_id'), 'friends', ['addressee_id'], unique=False)
    op.create_index(op.f('ix_friends_requester_id'), 'friends', ['requester_id'], unique=False)
    op.create_table('match_scores',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_a', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_b', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_a'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_b'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a', 'user_b', name='uq_match_scores_pair')
    )
    op.create_index(op.f('ix_match_scores_user_a'), 'match_scores', ['user_a'], unique=False)
    op.create_index(op.f('ix_match_scores_user_b'), 'match_scores', ['user_b'], unique=False)
    op.create_table('profiles',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('birthdate', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('statuses',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('status', postgresql.ENUM('watching', 'want_to_watch', 'completed', 'dropped', name='movie_status'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'movie_id', name='uq_statuses_user_movie')
    )
    op.create_index(op.f('ix_statuses_movie_id'), 'statuses', ['movie_id'], unique=False)
    op.create_index(op.f('ix_statuses_user_id'), 'statuses', ['user_id'], unique=False)
    op.create_table('swipes',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('movie_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('direction', postgresql.ENUM('like', 'dislike', name='swipe_direction'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swipes_movie_id'), 'swipes', ['movie_id'], unique=False)
    op.create_index(op.f('ix_swipes_user_id'), 'swipes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_swipes_user_id'), table_name='swipes')
    op.drop_index(op.f('ix_swipes_movie_id'), table_name='swipes')
    op.drop_table('swipes')
    op.drop_index(op.f('ix_statuses_user_id'), table_name='statuses')
    op.drop_index(op.f('ix_statuses_movie_id'), table_name='statuses')
    op.drop_table('statuses')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_match_scores_user_b'), table_name='match_scores')
    op.drop_index(op.f('ix_match_scores_user_a'), table_name='match_scores')
    op.drop_table('match_scores')
    op.drop_index(op.f('ix_friends_requester_id'), table_name='friends')
    op.drop_index(op.f('ix_friends_addressee_id'), table_name='friends')
    op.drop_table('friends')
    op.drop_index(op.f('ix_favorites_user_id'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_movie_id'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_dislikes_user_id'), table_name='dislikes')
    op.drop_index(op.f('ix_dislikes_movie_id'), table_name='dislikes')
    op.drop_table('dislikes')
    op.drop_index(op.f('ix_ai_recommendations_user_id'), table_name='ai_recommendations')
    op.drop_index(op.f('ix_ai_recommendations_movie_id'), table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('movies')
    # ### end Alembic commands ###
